# Generated by Django 5.1.2 on 2024-11-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1: Respective sticker pack (3 stickers)'), (2, 'Tier 2: Pouch (6 stickers)'), (3, 'Tier 3: Purple upcycled things (9 stickers)')], unique=True),
        ),
    ]
