# Generated by Django 5.1.2 on 2024-11-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reward_tier'),
        ('stickers', '0003_sticker_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='required_stickers',
            field=models.ManyToManyField(blank=True, related_name='rewards', to='stickers.sticker'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1: Respective sticker pack (3 stickers)'), (2, 'Tier 2: Pouch (6 stickers)'), (3, 'Tier 3: Purple upcycled things (9 stickers)'), (4, 'Tier 3: Tote bag (12 stickers)'), (5, 'Tier 3: Water bottle (15 stickers)')], unique=True),
        ),
    ]
